version: "3"

services:
  mysql:
    restart: always
    image: mysql:5
    container_name: acm-training-mysql
    hostname: acm-training-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - /srv/uestc-acm/acm-training-mysql:/var/lib/mysql
  server:
    image: ruinshe/acm-training:latest
    container_name: acm-training-server
    hostname: acm-training-server
    ports:
      - 8080:8080
