SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- whole database
DROP DATABASE IF EXISTS uestc_acm_training;

CREATE SCHEMA IF NOT EXISTS uestc_acm_training DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
USE uestc_acm_training;

-- user table
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    `name` VARCHAR(24) NOT NULL UNIQUE,
    `email` VARCHAR(100) NOT NULL UNIQUE,
    `phone` VARCHAR(45) NOT NULL UNIQUE,
    -- sha256sum
    `password` VARCHAR(130) NOT NULL UNIQUE,
    `rating` INT NOT NULL DEFAULT 1500) ENGINE = InnoDB;
